---
title: "final-evaluation-luchen"
output: html_document
date: "2024-03-08"
---

# Assignment Info

- **Student name:** Luchen Yu
- **Project title:** Correlations of Clinical Diagnostic Information and Demographic Information at Different Education Levels for OCD Patients
- **Submission date:** Mar 4 at 5:18pm

## Report plan summary

Dr. Dowling pointed out what I did improperly for the first plot I made, which is the frequency of OCD vs. education level bar plot. Due to the fact that the whole dataset is about patients who have diagnosed with OCD, nothing can be analyzed for the frequency of OCD. So, it’s meaningless to make a plot like that. It can only be a plot to present the dataset. To modify this plot, Dr. Dowling also suggested to make a proportion bar plot for education level and family history of OCD to predict anxiety disorders and/or depression disorders. I will try to make this plot. For the second plot I made, the boxplot for Y-BOCS score for compulsion and obsession across education levels, Dr. Dowling suggested to rank the x-axis from the lowest education level to the highest education level, which makes more sense logically. She also suggested that I can do a scatterplot for the Y-BOCS score for obsession vs. Y-BOCS score for compulsion.

	•	Figure
For the first figure, I will make a bar plot for education level and family history to predict anxiety disorder and depression disorder. For the second figure, I will keep my original boxplot for Y-BOCS score across education levels on both compulsion and obsession. For the third plot, I will make a scatterplot to see whether there’s a correlation between two types of Y-BOCS scores.
	•	Analysis
For the first figure, I will carry out a logistic regression model analysis to predict the occurrence of anxiety disorder and depression disorder for OCD patients at different education levels and have or do not have family history of OCD. For the second figure, I will perform ANOVA test for both compulsion and obsession scores for different education levels.
	•	Table
I will create an apa table for the summary of statistics results from the summarize() analysis for the second plot, including mean, median, min, max, and sd values for both compulsion score and obsession score for the four different education levels.
	•	Contribution of words
Since I did not collect data myself, there’s not much to mention in methods section. And since no major finding from the results, I will not write too much in discussion as well. So, I will distribute most of the words in introduction section and analysis section. In introduction, I will do the literature review on OCD related factors like family history of OCD, education level, etc., how these factors associate with OCD or each other. Then in analysis, I will describe as many as I can for the figure description and statistical analysis description. So, ideally all 10 references will go into the introduction.
	•	Code that can referent in text *(commented out, view in text editor)*
<!-- I will use cite the results from the ANOVA test to analyze the second plot on Y-BOCS scores across different education levels. For ANOVA test for obsession scores: -->
<!-- $F$() = `r round(summary(obsessions_anova)[[1]]$F[1],3)` for F value, and  -->
<!-- $p$() = `r round(summary(obsessions_anova)[[1]]$P[1],3)`  for p value. For ANOVA test for compulsion scores: -->
<!-- $F$() = `r round(summary(compulsions_anova)[[1]]$F[1],3)` for F value, and  -->
<!-- $p$() = `r round(summary(compulsions_anova)[[1]]$P[1],3)`  for p value. -->
	•	Goal for the final report
To apply what I have learned in class to deal with a real-life dataset. For example, use ggplot to make bar plot, scatter plot, and box plot to describe association and correlation between variables based on the dataset. And apply statistical analysis for these different plots, e.g. logistic regression model and ANOVA test in my case.

Additional comments: 

For the table part, it's meangless to have a summary table within the text, so I make a table for the proportions of anxiety diagnosis for Figure 1, including other information to summary Figure 1.
For the code referent in text, I feel like F value is not needed here because the ANOVA result is not significant. So I just cite two p values.

I only interpret the prediction of anxiety disorder situation no depression disorder because there are a lot to perform for this single prediction.

# Assessment

The lists of expectations in each category are to help you understand the kinds of things I'm looking for as I grade. These **do not** map onto point values. A checked box indicates the expectation was met or exceeded. (This also helps me spot patterns across students to identify ways I can improve the syllabus and lectures for future students.)

Ratings indicate overall success for each category and loosely map onto points. Starting from 20 points, no points are lost for the highest rating, -3 for the lowest, and somewhere in between for the middle ratings. Points lost in that range are dependent on how many issues there are, how much they matter, whether it's technicality vs problem of consequence, whether it's the same core issue that lost you points in a different section, whether exceeding expectations elsewhere compensate for a small issue, whether it's something we talked about in your report plan meeting, etc. 

Additional comments are included below the ratings as needed. Final project and class grades are included at the end of the document.

**WARNING: Grades for this assignment are going to be lower than you expect!** Don't freak out. I use "specs-based grading", which works very differently from the letter-grade-to-percentage conversion you are probably used to. It's more like Harry Potter OWLs -- 19/20 is outstanding, 16-18 exceeds expectations (not a C!), 13-15 meets expectations (not an F!), etc. You're not down to T(roll) until you're in the negatives. Remember this is only 20% of your final grade!

## .Rmd/PDF match

**Expectations:**

- [x] PDF submitted to Canvas is identical to the PDF created when I knit your .Rmd
- [x] Knitting does not produce any errors or problematic warnings

**Rating:**

- [x] Perfect match
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive error(s), missing PDF, or significant problems

*No additional comments*

## Data read-in, prep, wrangling

**Expectations:**

- [x] Data preparation and wrangling code present (may separate files)
- [x] Intermediate datasets (if used) are functional and read in successfully
- [x] Raw or intermediate data read into .Rmd code chunk
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

I appreciate your thorough commenting!!

## Figures, tables, analyses

### Figures

**Expectations:**

- [x] At least 2 plots are produced in .Rmd chunks (not imported images)
- [x] Figures are different kinds of plots 
- [x] Figures follow report plan (may have inconsequential deviations)
- [x] Figures are publication-quality
- [x] Figures are sensibly captioned with `fig.cap` chunk option
- [x] Figures are informative and interpretable
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

I recommend taking the color/fill legend out of Figure 3. Having the different colors is useful, but the legend itself is distracting. Typically when a reader sees a legend they assume it's important for interpreting the figure, so it's a little confusing at first.

### Table

**Expectations:** 

If you included more than the one required table, only one needs to meet expectations.

- [x] At least 1 table is produced in .Rmd chunk
- [x] Table follows report plan (may have inconsequential deviations)
- [ ] Table is publication-quality
- [x] Table is sensibly captioned within the function (e.g., the kable caption argument)
- [x] Table is informative and interpretable
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

To be publication-ready you need to have the column names listed in plain English and APA formatting rather than appearing as the literal variable names. e.g., "Anxiety.Diagnosis" -> "Anxiety Diagnosis" and "Count2" -> "Count

I think you can rework both your tables to be easier to interpret. Actually I think they can be just one single table, or can at least be presented in one "package". Rather than summarizing data like you've done here (which definitely does work!), you can make use of functions designed to calculate proportions, like proportions()/prop.table(). In the current format it's not immediately clear what proportion you're actually reporting (percent across everything? across diagnosis status? across education level?)

### Analysis

**Expectations:**

If you included more than the one required analysis (or other requirements agreed on in the report plan), only one needs to meet expectations.

- [x] At least 1 statistical analysis is executed in .Rmd chunk (or sourced code if appropriate)
- [x] Analysis follows report plan (may have inconsequential deviations)
- [x] Analysis is executed correctly
- [x] Analysis is appropriate (not necessarily ideal) for data type(s) and research questions
- [x] Analysis is referenced and interpreted in narrative text
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

*No additional comments*

## Manuscript

### Narrative text

**Expectations:**

- [x] Narrative text includes 1500+ words distributed across 4 sections
- [x] Sufficient literature review (per report plan)
- [x] Sufficient methods section (per report plan)
- [ ] Sufficient results section (per report plan)
- [x] Sufficient discussion (per report plan)
- [x] Narrative provides sufficient context and interpretation for all figures, tables, and analyses
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

This is kind of big-picture, but you can much more precise in presenting your data throughout your narrative, and in the results section in particular. This is also where in-text r code is very valuable. For example, rather than saying "X is more than Y", say "X (n=`r count(myVarX)[[1]]`) is more than Y (n=`r count(myVarY)[[1]]`).

### Markdown

**Expectations:**

- [x] Figures and tables are successfully referenced with markdown syntax
- [x] At least 2 in-text code references
- [x] At least 1 in-text code reference includes in-text function
- [ ] R Markdown is used effectively to follow APA format (e.g., headings, emphasized text)
- [x] YAML header is functional and complete
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [ ] At least one minor problem
- [x] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

For headings, the `#` sign(s) will format things correctly for the appropriate heading level. If you add extra formatting (like bold) it can override the APA-styling.

Some small odd things, like `$p$()`. What are the parentheses supposed to be doing?

Don't refer to variables by their literal variable names; use reader-friendly plain English (e.g., "differences in Y.BOCS.Score" -> "differences across individuals' Y-BOCS scores")

Your chunk output should not display verbatim in your manuscript (p10, 11, 13, 14). This output needs to be reported in table form, or (if appropriate) you can just use in-text r code to extract and print the relevant elements within your narrative text (like betas and p-values of significant effects).
 
### BibTeX

**Expectations:**

- [x] At least 10 in-text citations using BibTeX reference syntax
- [x] In-text citations are rendered without errors
- [x] In-text citations have no obvious problems (e.g., incorrect special characters)
- [x] R and R packages are cited in-text using `cite_r()`
- [x] References page renders without errors
- [x] References page is APA formatted and free of obvious problems
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Some of your references are missing years (will show up as no date or "n.d.")

## GitHub & best practices

These expectations will not have an impact on your grade unless there are egregious issues, but I include them to give you feedback on what you can do if you use this workflow going forward.

**Expectations:**

- [x] GitHub repo and contained files are sensibly and informatively named
- [ ] GitHub repo is well-structured and tidy
- [x] GitHub README.md file is informative
- [ ] Commit messages are informative
- [x] Style is (relatively) consistent
- [x] Comments are frequent and informative
- [ ] Code chunks have informative names, follow 1-chunk-1-thing rule, and are distributed throughout the text

*No additional comments*

## Overall

Nice job, Luchen! Your figures and tables are much cleaner and more informative than when I last saw them. At this point you can still work more on the finer points of using R Markdown, but it's clear that you have a good grasp of the material we've covered this quarter!

# Grade

- **Final report grade:** 16
- **Class participation grade:** 20
- **Weekly assignments:** 60
- **TOTAL Final course grade:** # of 96 (A)
